### ISSUE TITLE
Verandering van grid op basis van geselecteerde button?

### ISSUE THREAD

**Issue by PipHarsveld** [PipHarsveld/Hallo-Strandeiland#65]
Ik heb code voor het masonry grid en ik heb code voor het rechte grid, maar het lukt me nog niet om de styling aan de radiobuttons te koppelen. Hoe zorg ik ervoor dat er andere styling wordt toegepast op het moment dat een bepaalde radiobutton is selected?

Dit werkt bijvoorbeeld niet:
```css
  .gridBtn>input:checked+.grid{
    grid-template-rows: auto;
  }
```

**Comment by Inevdhoven** [comment]
Ik ga er naar kijken of ik een oplossing weet

**Comment by Inevdhoven** [comment]
De selector klopte niet, dit heb ik aangepast naar:

```css
.filterBar:has(form:nth-of-type(2) .gridBtn>input:checked) + .themeFilters + .grid{
    grid-template-rows: auto;
    background-color: red;
}
```
